Demo_Manage/Demo_Manage/Models/Class.cs
namespace Demo_Manage.Models
{
    public class Class
    {
        public int ClassID { get; set; }
        public string NameClass { get; set; }
        public string Faculty { get; set; }
    }
}

Demo_Manage/Demo_Manage/Models/ContextDB.cs
using Microsoft.EntityFrameworkCore;

namespace Demo_Manage.Models
{
    public class ContextDB : DbContext
    {
        public ContextDB(DbContextOptions<ContextDB> options) : base(options)
        {
            
        }
        public DbSet<Class>Classes { get; set; }
        public DbSet<Student>Students { get; set; }  
    }
}
//EntitySet: DbContext chứa tập thực thể (DbSet<TEntity>) cho tất cả thực thể nối với những bảng của CSDL.

Demo_Manage/Demo_Manage/Models/ErrorViewModel.cs
using System;

namespace Demo_Manage.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Demo_Manage/Demo_Manage/Models/Student.cs
namespace Demo_Manage.Models
{
    public class Student
    {
        public int StudentID { get; set; }
        public string NameStudent { get; set; }
        public string Addr { get; set; }
    }
}

Demo_Manage/Demo_Manage/Controllers/ClassController.cs
using Demo_Manage.Models;
using Demo_Manage.Service.ClassService;
using Microsoft.AspNetCore.Mvc;

namespace Demo_Manage.Controllers
{
    public class ClassController : Controller
    {
        private IClassService _classService;

        public ClassController(IClassService classService)
        {
            _classService = classService;
        }
        
        // Get:Class/
        [HttpGet]
        public IActionResult Index()
        {
            return View(_classService.GetAll());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Class clas)
        {
            _classService.Add(clas);
            _classService.Save();
            return RedirectToAction("Index");
        }
        
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var getId = _classService.GetById(id);
            return View(getId);
        }
        
        [HttpPost]
        public IActionResult Edit(Class clas)
        {
            _classService.Update(clas);
            _classService.Save();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            _classService.Delete(id);
            _classService.Save();
            return RedirectToAction("Index");
        }
    }
}

Demo_Manage/Demo_Manage/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Demo_Manage.Models;
using Microsoft.AspNetCore.Server.Kestrel.Core;



namespace Demo_Manage.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }

        /*public ActionResult UploadImage()
        {
            return View();
        }

        public string ProcessUpload(HttpPostAttribute file)
        {
            // xử lý upload
            file.SaveAs(ServerAddress.MapPath("~/wwwroot/images"+file.FileName));            
            return "/wwwroot/images/" + file.FileName;    
        }*/
    }
}

Demo_Manage/Demo_Manage/Controllers/StudentController.cs
using Demo_Manage.Models;
using Demo_Manage.Reponsitory.StudentReponsitory;
using Demo_Manage.Service.StudentService;
using Microsoft.AspNetCore.Mvc;
using Demo_Manage.Service.StudentService;
namespace Demo_Manage.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentService _studentService;

        // Constant giá trị của nó không thể thay đổi trong suốt chương trình/
        // Readonly cũng tương tự như Constant nhưng điểm khác biệt là
        // các bạn có thể thay đổi giá trị của nó nhưng chỉ được phép thay đổi trong Contructor mà thôi.
        public StudentController(IStudentService studentService)
        {
            _studentService = studentService;
        }
        
        // Get: //Student/
        [HttpGet]
        public IActionResult Index()
        {
            return View(_studentService.GetAll());
            
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Student student)
        {
            _studentService.Add(student);
            _studentService.save();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var getId = _studentService.GetById(id);
            return View(getId);
        }

        [HttpPost]
        public IActionResult Edit(Student student)
        {
            _studentService.Update(student);
            _studentService.save();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            _studentService.Delete(id);
            _studentService.save();
            return RedirectToAction("Index");
        }
    }
}
// * : Nếu ta muốn trả về View cho trình duyệt, ta gọi phương thức View ().
// Nếu ta muốn chuyển hướng người dùng từ một hành động điều khiển sang hành động khác,
// ta gọi phương thức RedirectToAction ().

// * :Trong hầu hết các trường hợp, một hành động của bộ điều khiển trả về ViewResult. 

Demo_Manage/Demo_Manage/Pages/Home/UploadImage.cshtml
@model object

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
<style type="text/css">.form- { }</style>

<h2>Upload Image</h2>
<div class="form-"inline>
    chọn ảnh : <input type="text" name="picture" id="picture" class="form-control"/>
    <input type="file" id="filepUload" accept="image/*" name="fileUpload" style="display: none;"/>
    <input type="button" value="..." class="btn btn-success"/>
</div>
<img id="pictureUpload" witdh="300"/>

@section upload
{
    <script>
        $(function() {
             // đăng ký sự kiện click nút btnUpload.
            $('#btnUpload').click(function() {
                $('#fileUpload').trigger('click'); 
//.trigger(): Thực hiện tất cả các xử lý và đính kèm các loại sự kiện nhất định tới thành phần được chọn.trigger(Sự kiện,Tham số).              
            });
           // bắt sự kiên change data của fileUpload.
            $('#fileUpload').change(function() {
           // kiểm trình duyệt có hỗ trợ formData bject ko ?
                if (window.FormData !== undefined) 
                {
                    // lấy dữ liệu fileUpload.
                    var fileUpload = $('#fileUpload').get(0);
                    var files = fileUpload.files;
                    // tạo đối t ượngformdata.
                    var formData = new FormData();
                    // Đưa dữ liệu vào form.
                    formData.append('file', files[0]);
                    // POST form Data lên server
                    $.ajax(
                        {
                            type: 'POST',
                            url: '/HomeControllrer/ProcessUpload',
                            contentType: false, // không có header
                            processData: false, // không xử lý dữ liệu
                            data: formData,
                            success: function(urlImage) {
                                $('#pictureUpload').attr('src', urlImage);
                                $('#picture').val(urlImage);
                            },
                            error: function(err) {
                                alert('lỗi upload:' + err.statusText);
                            }
                });
                }
            });
        });
    </script>
}
@* * khi kích vào upload thì thực thi sự kiện click().
 khi sự kiện click() xảy ra, thì nó thực thi 1 function() . 
 sự kiện click ở đay là --> $('#filepUload')=> truy cập vào file upload.=>"mở cửa sổ upload lên"  *@
 
 @* note: khi ta click vào button ... => mở cửa sổ chọn tệp tin *@

Demo_Manage/Demo_Manage/Views/Class/Create.cshtml
@model Demo_Manage.Models.Class

<!DOCTYPE html>

<html>
<head>
    <title>Add </title>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="NameClass" class="control-label"></label>
                    <input asp-for="NameClass" class="form-control" />
                    <span asp-validation-for="NameClass" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Faculty" class="control-label"></label>
                    <input asp-for="Faculty" class="form-control" />
                    <span asp-validation-for="Faculty" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                    <a class="text-dark btn btn-primary" asp-area="" asp-controller="Class" asp-action="Index">Back</a>
                </div>
            </form>
        </div>
    </div>
</div>
</body>
</html>

Demo_Manage/Demo_Manage/Views/Class/Edit.cshtml
@model Demo_Manage.Models.Class

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Edit</h2>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-12">
            <form method="post" asp-controller="Student" asp-action="Edit">
                <input type="hidden" class="form-control" asp-for="ClassID">
                <div class="form-group">
                    <label asp-for="NameClass" class="control-label"></label>
                    <input asp-for="NameClass" class="form-control" />
                    <span asp-validation-for="NameClass" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Faculty" class="control-label"></label>
                    <input asp-for="Faculty" class="form-control" />
                    <span asp-validation-for="Faculty" class="text-danger"></span>
                </div>
                
                <input class="btn btn-primary" type="submit" value="Save"/>
                <a class=" text-dark btn btn-primary" asp-area="" asp-controller="Class" asp-action="Index">Back</a>
            </form>
        </div>
    </div>
</div>

Demo_Manage/Demo_Manage/Views/Class/Index.cshtml
@model System.Collections.Generic.IEnumerable<Demo_Manage.Models.Class>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src='https://kit.fontawesome.com/a076d05399.js'></script>
<script src="https://use.fontawesome.com/49b98aaeb5.js"></script>
<h2>Bạn đang ở trang Index</h2>
<div class="m-auto">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        @*<img src="http://cunglamseo.com/images/cung-lam-seo-logo.png" alt="cùng làm SEO"/>*@
                        
                        <h2>Request List</h2>
                        @*Icon mobile, facebook*@
                            
                        <div class="row mobile-hotline">
                            <div class="col-md-6 mobile-hotline-left">
                                <a href="http://www.messenger.com/t/joseph.thien.75" target="blank">
                                    <i class='fab fa-facebook-messenger' style='font-size: 36px; color:blue'></i>
                                </a>
                            </div>
                                
                            <div class="col-md-6 mobile-hotline-right">
                                <a href="tel:+84972939830" target="blank"><i style="font-size: 50px; color:blue" class="fa fa-mobile" aria-hidden="true"></i> </a>
                            </div>
                        </div>
              
                        <a asp-action="Create" class="btn btn-primary">Create <i class='fas fa-plus-square'></i></a>

                    </div>
                  
                       
                    
                   
                    <div class="x_content">
                        <table class="table">
                            <thead>
                            <tr style="color:red">
                               
                                <th> Code Student </th>    
                                <th > Name </th>
                                <th> address </th>
                            </tr>    
                            </thead>
                            <tbody>
                            <style>
                                /* Add Facebook and SĐT */
                                .mobile-hotline {
                                    display: -moz-box;
                                    /*width: 150px;
                                    height: 150px;*/    
                                    
                                }
                                .hotline {position: fixed;
                                    left: 10px;
                                    bottom: 10px;
                                    z-index: 9000;
                                    display: block;
                                    background: #fac100;
                                    color: red;
                                    padding-top: 5px;padding-bottom:5px; padding-left:12px; padding-right: 12px;
                                    border-radius: 99px;}
                                .hotline .hotline-number{font-size:20px; color: #b20000; font-weight: bold}
 
                                @@media  (max-width: 767px) {
 
                                    .hotline{
 
                                        display :none;
 
                                    }
                                    .mobile-hotline{display: block; bottom: 0; width: 100%; background:rgba(0,0,0,0.5); height: 60px; position: fixed; z-index: 9999999;}
                                    .mobile-hotline .mobile-hotline-left{width: 45%; float: left; text-align: center; background: blue; margin-left: 10px; margin-right:5px; margin-top: 7px; height: 45px; border-radius: 4px;}
                                    .mobile-hotline .mobile-hotline-left a{color: white; line-height: 46px; font-size:16px; font-weight: bold}
 
                                    .mobile-hotline .mobile-hotline-right{width: 45%; float: right; text-align: center; background: #fac100; margin-left: 5px; margin-right: 10px; margin-top: 7px; height: 45px; border-radius: 4px; color: blue}
                                    .mobile-hotline .mobile-hotline-right a{color: red; line-height: 46px; font-size: 16px; font-weight: bold}
                                }
                                 
                            </style>
                            <a href="tel:+84972939830"><div class="hotline">
                                <span class="before-hotline">Hotline:</span>
                                <span class="hotline-number">0972.939.830</span>
                            </div></a>
                           
                            @foreach (var item in Model)
                            {

                                <tr class="text-left">
                                    <td> @Html.DisplayFor(modelItem => item.ClassID)</td>
                                    <td> @Html.DisplayFor(modelItem => item.NameClass)</td>
                                    <td> @Html.DisplayFor(modelItem => item.Faculty)</td>

                                    <td>
                                        <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.ClassID">Edit <i class="fa fa-edit"></i></a>
                                        <a class="btn btn-primary" asp-action="Delete" asp-route-id="@item.ClassID"><i class="fa fa-trash"></i>Delete</a>
                                        @* <a class="btn btn-primary" asp-action="Delete" asp-route-id="@item.StudentID” onclick=“return confirm('bạn có chắc chắn muốn xóa');">Delete</a> *@
                                    </td>
                                </tr>
                            }
                            
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Demo_Manage/Demo_Manage/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Demo_Manage/Demo_Manage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo_Manage</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
             
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Demo_Manage</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student</a>
                        </li>
                        <li class="nav-item">
                            <a style="color:blue" class="nav-link text-dark" asp-area="" asp-controller="Class" asp-action="Index">Class</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Demo_Manage - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
<script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
    @RenderSection("upload", required: false)
    
</body>
</html>

Demo_Manage/Demo_Manage/Views/Student/Create.cshtml
@model Demo_Manage.Models.Student

<!DOCTYPE html>

<html>
<head>
    <title>Add </title>
</head>
<body>
      <div class="container-fluid">
          <div class="row">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                  <form asp-action="Create">
                      <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                      <div class="form-group">
                          <label asp-for="NameStudent" class="control-label"></label>
                          <input asp-for="NameStudent" class="form-control" />
                          <span asp-validation-for="NameStudent" class="text-danger"></span>
                      </div>
                      <div class="form-group">
                          <label asp-for="Addr" class="control-label"></label>
                          <input asp-for="Addr" class="form-control" />
                          <span asp-validation-for="Addr" class="text-danger"></span>
                      </div>
                      <div class="form-group">
                          <input type="submit" value="Create" class="btn btn-primary" />
                          <a class="text-dark btn btn-primary" asp-area="" asp-controller="Student" asp-action="Index">Back</a>
                      </div>
                  </form>
              </div>
          </div>
      </div>
</body>
</html>

Demo_Manage/Demo_Manage/Views/Student/Edit.cshtml
@model Demo_Manage.Models.Student

@{
    ViewBag.Title = "Sữa Thông Tin";
    Layout = "_Layout";
}

<h2>Edit</h2>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-12">
            <form method="post" asp-controller="Student" asp-action="Edit">
                <input type="hidden" class="form-control" asp-for="StudentID">
                <div class="form-group">
                    <label asp-for="NameStudent" class="control-label"></label>
                    <input asp-for="NameStudent" class="form-control" />
                    <span asp-validation-for="NameStudent" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Addr" class="control-label"></label>
                    <input asp-for="Addr" class="form-control" />
                    <span asp-validation-for="Addr" class="text-danger"></span>
                </div>
                
                <input class="btn btn-primary" type="submit" value="Save"/>
                <a class=" text-dark btn btn-primary" asp-area="" asp-controller="Student" asp-action="Index">Back</a>
            </form>
        </div>
    </div>
</div>

Demo_Manage/Demo_Manage/Views/Student/Index.cshtml
@model System.Collections.Generic.IEnumerable<Demo_Manage.Models.Student>

@{
    ViewBag.Title = "Index Student";
    Layout = "_Layout";
}
@* <img src="http://banners.wunderground.com/banner/gizmotimetemp_both/ *@
@* language/www/global/stations/48852.gif"alt="Du bao thoi tiet - Co do Hue" title="Dự báo thời tiết - Cố đô Huế" height="41" width="127"> *@
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src='https://kit.fontawesome.com/a076d05399.js'></script>
<script src="https://use.fontawesome.com/49b98aaeb5.js"></script>
<style type="text/css">.icon-warning-sign { }
</style>
@* //text hiệu ứng *@
@* băng tải ngang *@
@* <marquee style="z-index: 1; left: 10px; width: 770px; position: absolute; top: 20px; height: 1000px;" scrollamount="5" direction="right"> *@
@*     <span class="falling1"> *@
@*         <img src="http://d.violet.vn/uploads/resources/161/0.horses_76.gif" _fcksavedurl="http://www.blinkyou.com/falling/images/hotpinkflower.gif" _fcksavedurl="http://www.blinkyou.com/falling/images/hotpinkflower.gif"> *@
@*     </span> *@
@* </marquee> *@

@* <marquee style="z-index: 1; left: 677px; width: 50px; position: absolute; top: -11px; height: 1000px;" scrollamount="2" direction="down"> *@
@*     <span class="falling1"><i class='fas fa-heart' style='font-size:32px;color:red'></i></span></marquee> *@
@* <marquee><i class='fas fa-heart' style='font-size:32px;color:red'></i></marquee> *@

<marquee style="z-index: 2; left: 660px; width: 46px; position: absolute; top: -6px; height: 900px;" scrollamount="3" direction="down">
    <span class="falling1"><i class='fas fa-heart' style='font-size:32px;color:red'></i></span></marquee>
<marquee style="z-index: 3; left: 660px; width: 46px; position: absolute; top: -6px; height: 900px;" scrollamount="4" direction="down">
    <span class="falling1"><i class='fas fa-heart' style='font-size:32px;color:red'></i></span></marquee>
<marquee style="z-index: 4; left: 660px; width: 46px; position: absolute; top: -6px; height: 900px;" scrollamount="5" direction="down">
    <span class="falling1"><i class='fas fa-heart' style='font-size:32px;color:red'></i></span></marquee>
<marquee style="z-index: 5; left: 660px; width: 46px; position: absolute; top: -6px; height: 900px;" scrollamount="6" direction="down">
    <span class="falling1"><i class='fas fa-heart' style='font-size:32px;color:red'></i></span></marquee>
<marquee style="z-index: 6; left: 660px; width: 46px; position: absolute; top: -6px; height: 900px;" scrollamount="7" direction="down">
    <span class="falling1"><i class='fas fa-heart' style='font-size:32px;color:red'></i></span></marquee>
<marquee style="z-index: 2; left: 660px; width: 46px; position: absolute; top: -6px; height: 900px;" scrollamount="8" direction="down">
    <span class="falling1"><i class='fas fa-heart' style='font-size:32px;color:red'></i></span></marquee>
<marquee style="z-index: 2; left: 660px; width: 46px; position: absolute; top: -6px; height: 900px;" scrollamount="9" direction="down">
    <span class="falling1"><i class='fas fa-heart' style='font-size:32px;color:red'></i></span></marquee>
<marquee style="z-index: 2; left: 660px; width: 46px; position: absolute; top: -6px; height: 900px;" scrollamount="10" direction="down">
    <span class="falling1"><i class='fas fa-heart' style='font-size:32px;color:red'></i></span></marquee>
<marquee style="z-index: 2; left: 660px; width: 46px; position: absolute; top: -6px; height: 900px;" scrollamount="1" direction="down">
    <span class="falling1"><i class='fas fa-heart' style='font-size:32px;color:red'></i></span></marquee>
<marquee style="z-index: 2; left: 660px; width: 46px; position: absolute; top: -6px; height: 900px;" scrollamount="2" direction="down">
    <span class="falling1"><i class='fas fa-heart' style='font-size:32px;color:red'></i></span></marquee>


@* $1$ End hiệu ứng #1# *@
<h2>Index Student</h2>
<i class="icon-warning-sign" style="color:red"></i>

<div class="m-auto">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <i class='fas fa-heart' style='font-size:32px;color:red'></i>
                        <i class='fas fa-heart' style='font-size:32px;color:red'></i>
                       
                    </div>    
                    <a asp-action="Create" ><button style="color:blue" style='font-size:24px'>Create <i style="color:blue" class='fas fa-plus-square'></i></button></a>
                    <div class="x_content">
                        <table class="table">
                            <thead>
                            <tr style="color:blue">
                               
                                <th> Code Student </th>
                                <th> Name </th>
                                <th> Address </th>
                                <th style="color:red"> Action </th>
                            </tr>    
                            </thead>
                            <tbody>
                            @foreach (var item in Model)
                            {
                             
                                <tr class="text-left">
                                    <td> @Html.DisplayFor(modelItem => item.StudentID)</td> 
                                    <td> @Html.DisplayFor(modelItem => item.NameStudent)</td>
                                    <td> @Html.DisplayFor(modelItem => item.Addr)</td>
                                   
                                    <td>
                                        <a  asp-action="Edit" asp-route-id="@item.StudentID"><button style="color:blue" style= " font-size:18px">Edit <i style="color:blue" class="fa fa-edit"></i></button></a> ||
                                        <a  asp-action="Delete"  asp-route-id="@item.StudentID"><button style="color:red" style="font-size:18px">Delete<i style="color:red" class="fa fa-trash"></i></button></a>
                                       @* <a class="btn btn-primary" asp-action="Delete" asp-route-id="@item.StudentID” onclick=“return confirm('bạn có chắc chắn muốn xóa');">Delete</a> *@
                                    </td>
                                </tr>
                            }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>